find_package(CUDAToolkit)
if (CUDAToolkit_FOUND)
    message(NOTICE "CUDAToolkit found")
    message(STATUS "CUDAToolkit Version: ${CUDAToolkit_VERSION}")
    message(STATUS "CUDAToolkit INCLUDE: ${CUDAToolkit_INCLUDE_DIRS}")

    include_directories(${CUDAToolkit_INCLUDE_DIRS})
else()
    message(WARNING "CUDAToolkit not found")
endif(CUDAToolkit_FOUND)

#find_package(CUDA)
#if(CUDA_FOUND)
#    message(NOTICE "CUDA found")
#    message(STATUS "CUDA Version: ${CUDA_VERSION_STRING}")
#    message(STATUS "CUDA Libs: ${CUDA_LIBRARIES}")
#    include_directories(${CUDA_INCLUDE_DIRS})
#else()
#    message(WARNING "CUDA not found")
#endif(CUDA_FOUND)

